In [6]:
import numpy as np, matplotlib.pyplot as plt, itertools

In [ ]:
class Pool(object):
    def __init__(self, size, noise=0.0):
        self.net = np.zeros(size)
        self.act = np.zeros(size)

    def clamp(self, a):
        # This should make sure that activation of clamped units remains fixed by given value no matter what
        self.act = a


class Projection(object):
    def __init__(self):
        pass


class Network(object):
    def __init__(self, estr, alpha, gamma, pools=[]):
        self.estr = estr
        self.alpha = alpha
        self.gamma = gamma
        self.pools = pools
        self.econns = {}
    
    def make_connections(self, default_e=1.0, default_i=-1.0):
        # Create a matrix for each pair
        if len(self.pools) > 1:
            for pair in itertools.combinations(self.pools, 2):
                self.econns[pair] = np.full(shape=[pair[0].size, pair[1].size], fill_value=default_e)
            for pool in self.pools:
                self.iconns[pool] = np.full(shape=[pool.size, pool.size], fill_value=default_i)
                np.fill_diagonal(self.iconns[pool], 0)

    def reset(self):
        pass

    def getnet(self):
        # FOR EACH POOL
        # Accumulate excitatory inputs
        for pair, econn in self.econns.items():
            pair[0].net += econn.dot(pair[1])
            pair[1].net += econn.T.dot(pair[0])
            
        # Accumulate inhibitory inputs and add noise
        for pool, iconn in self.iconns.items():
            pool.net = iconn.dot(pool)

        # Add noise to scaled external input

        # return net input
        pass

In [22]:
a = -np.ones([5, 5])
np.fill_diagonal(a, 0)
print(a)

[[ 0. -1. -1. -1. -1.]
 [-1.  0. -1. -1. -1.]
 [-1. -1.  0. -1. -1.]
 [-1. -1. -1.  0. -1.]
 [-1. -1. -1. -1.  0.]]
